
ALTER TABLE LOGEMENT
ADD
CONSTRAINT FK_ACHAT FOREIGN KEY(id_achat);

ALTER TABLE LOGEMENT
ADD
CONSTRAINT FK_RESERVATION FOREIGN KEY(id_reservation);

ALTER TABLE LOGEMENT
ADD
CONSTRAINT FK_ADRESSE FOREIGN KEY(id_adresse);

ALTER TABLE LOGEMENT
ADD
CONSTRAINT FK_CATEGORIE FOREIGN KEY(id_categorie);

ALTER TABLE LOGEMENT
ADD
CONSTRAINT FK_PROPRIETAIRE FOREIGN KEY(id_proprietaire);