
ALTER TABLE LOGEMENT
ADD
CONSTRAINT FK_QUARTIER FOREIGN KEY(FK_QUARTIER) REFERENCES QUARTIER(ID_QUARTIER);


ALTER TABLE LOGEMENT
ADD
CONSTRAINT FK_PROPRIETAIRE FOREIGN KEY(FK_PROPRIETAIRE) REFERENCES PROPRIETAIRE(ID_PROPRIETAIRE);

