ALTER TABLE PUBLICATION
ADD
CONSTRAINT FK2_ADRESSE FOREIGN KEY(id_adresse) REFERENCES ADRESSE(id_adresse);


ALTER TABLE PUBLICATION
ADD
CONSTRAINT FK2_PROPRIETAIRE FOREIGN KEY(id_proprietaire) REFERENCES PROPRIETAIRE(id_proprietaire);