  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (4,'Boys', 'scott', 648484848 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (1,'dariau','paul', 648484840 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (3,'dael' ,'tousse', 648484841 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (2,'devan', 'toure', 648484842 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (5,'florent', 'tadie', 648484843);
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (0,'rusel', 'rebelle', 648484844 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (4,'boycard', 'bob', 648484845 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (8,'bradley', 'marley', 648484846 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (7,'miguel', 'scott', 648484847 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (6,'daren', 'mark', 648484849);
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (9,'xavier', 'raoul', 648484801 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (10,'nathan', 'frost', 648484802);
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (11,'axel', 'blaze', 648484803 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (12,'olivier', 'tom', 648484804 );

  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (13,'shown', 'blake', 648484805 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (14,'jaden', 'franc', 648484806 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (15,'devis', 'erwin', 648484807 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (16,'lontsi', 'hernandez', 648484808 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (17,'ndendo', 'bradley', 648484809 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (18,'keubou', 'darelle', 648484810 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (19,'manguito', 'orlane', 648484811 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (20,'willy', 'pablo', 648484812 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (21,'jack', 'stone', 648484813 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (22,'black', 'white', 648484814 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (23,'paolo', 'bianki', 648484815 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (24,'joe', 'bideon', 648484816 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (25,'trust', 'parker', 648484817 );
  insert into CLIENT (id_client,nom_client,prenom_client,num_tel_client) values (26,'adele', 'stark', 648484818 );

