prompt ****************************** RECHERCHE UN LOGEMENT *******************************
PROMPT ************************************************************************************


set define on 


SELECT TYPE_LOGEMENT "TYPE DE LOGEMENT", NBR_CHAMBRE||' '||'Chambre(s)' "NOMBRE DE CHAMBRES", NBR_DOUCHE||' '||'Douche(s)' "NOMBRE DE DOUCHES" , PRIX_MENSUEL "PRIX MENSUEL", 
NOM_QUARTIER, NOM_PROPRIETAIRE||' '||PRENOM_PROPRIETAIRE "NOM PROPRIETAIRE"
FROM VILLE V 
JOIN QUARTIER Q 
ON (V.ID_VILLE = Q.FK_VILLE)
JOIN LOGEMENT L
ON (L.FK_QUARTIER = Q.ID_QUARTIER)
JOIN PROPRIETAIRE P 
ON (P.ID_PROPRIETAIRE = L.FK_PROPRIETAIRE)
WHERE TYPE_LOGEMENT LIKE '&TYPE_LOGEMENT' AND NOM_VILLE LIKE '&NOM_VILLE' AND 
PRIX_MENSUEL BETWEEN &prixMinimal AND &PrixMaximal 
AND NBR_CHAMBRE LIKE &Nbre_de_chambre AND NBR_DOUCHE LIKE &Nbre_de_douche
AND AVEC_PARKING LIKE '&Avec_parking' AND AVEC_PISCINE LIKE '&AvecPiscine';

@Menu\Menu_principal_client.sql



